# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b583aba22dc6a39a824a889767e1a9990026ebe067194111a21764c94a911d55c2f558b48b8190da9f54110d0a6b18433b66b8b0ab3979d03b2cda46339f87c9

test:
  secret_key_base: cfca3c1514f98f1a877ed2e173089b6e66eaea31318b1101c5170b851a0655929892f205be2b36e84770156d0131db8a9f178be5f5d9f2bf0db14b431133be58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
